# Generated by Django 2.2.7 on 2019-11-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='series/posts')),
                ('picture_banner', models.ImageField(blank=True, null=True, upload_to='seasons/baner')),
                ('banner_state', models.CharField(choices=[('AC', 'Active'), ('DC', 'Deactivate')], default='DC', max_length=2)),
                ('state', models.CharField(choices=[('EM', 'En emisión'), ('TR', 'Terminado'), ('PR', 'Próximamente')], default='EM', max_length=12)),
                ('sinopsis', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(default='Temporada 1', max_length=14)),
                ('state', models.CharField(choices=[('EM', 'En emisión'), ('TR', 'Terminado'), ('PR', 'Próximamente')], default='EM', max_length=12)),
                ('new_episode', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('episode', models.CharField(default='Episodio 1', max_length=13)),
                ('sinopsis', models.TextField(blank=True)),
                ('URL_video', models.URLField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Seasons')),
            ],
        ),
    ]
